# default config.yml

# map size
maps-max: 5000
maps-min: -2500

# time between two chest generate
time: 18000

# total number of kits 
kit-number: 3

# kits available in chest 
chests:
  kit1:
    - DIAMOND_HELMET 1 DURABILITY,1 PROTECTION_ENVIRONMENTAL,2
    - DIAMOND_CHESTPLATE 1 DURABILITY,1 PROTECTION_ENVIRONMENTAL,2
    - DIAMOND_LEGGINGS 1 DURABILITY,1 PROTECTION_ENVIRONMENTAL,2
    - DIAMOND_BOOTS 1 DURABILITY,1 PROTECTION_ENVIRONMENTAL,2 
  kit2:
    - COBBLESTONE 64
  kit3:
    - GOLD_HELMET 1 DURABILITY,1 PROTECTION_ENVIRONMENTAL,2
    - LEATHER_CHESTPLATE 1 DURABILITY,1 PROTECTION_ENVIRONMENTAL,2
    - LEATHER_LEGGINGS 1 DURABILITY,1 PROTECTION_ENVIRONMENTAL,2
    - LEATHER_BOOTS 1 DURABILITY,1 PROTECTION_ENVIRONMENTAL,2 
